const state={lang:localStorage.getItem("kt_lang")||"kr",places:[],cities:[],districts:[],guides:[],alerts:[],category:"all",query:"",sort:"default",user:null,map:null,userMarker:null,markers:[],view:localStorage.getItem("kt_view")||"grid",city:"",district:""};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const t=k=>(window.I18N?.[k]||k);
function tx(obj){return obj?.[state.lang]||obj?.en||obj?.kr||""}
function esc(v){return String(v??"").replace(/[&<>"\']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","\'":"&#39;"}[m]))}
function km(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(c-a),dLon=rad(d-b),x=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function google(lat,lng){return "https://www.google.com/maps/dir/?api=1&destination="+encodeURIComponent(lat+","+lng)}
function waze(lat,lng){return "https://waze.com/ul?ll="+encodeURIComponent(lat+","+lng)+"&navigate=yes&utm_source=kurdistan_tourism"}
function isSaved(id){return JSON.parse(localStorage.getItem("kt_saved")||"[]").includes(id)}
function savedIds(){return JSON.parse(localStorage.getItem("kt_saved")||"[]")}
function updateSavedCount(){$("#savedCount").textContent=savedIds().length}
function toggleSaved(id){let a=savedIds();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem("kt_saved",JSON.stringify(a));updateSavedCount();renderPlaces();renderSaved();if($("#modal").classList.contains("open"))openPlace(id)}
function typeLabel(type){return t(type)||type}
function applyI18n(){document.documentElement.lang=state.lang==="kr"?"ckb":state.lang;document.documentElement.dir=state.lang==="en"?"ltr":"rtl";$$("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));$$("[data-i18n-placeholder]").forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));$("#langSelect").value=state.lang;renderPlaces();renderCities();renderDistricts();renderGuides();renderAlerts();renderSaved();updateSavedCount()}
async function loadJSON(p){const r=await fetch(p,{cache:"no-store"});if(!r.ok)throw Error(p+" "+r.status);return r.json()}
async function boot(){try{$("#placeGrid").innerHTML='<div class="loading">'+t("loading")+"</div>";const [i,p,c,d,g,a]=await Promise.all([loadJSON("i18n/"+state.lang+".json"),loadJSON("data/places.json"),loadJSON("data/cities.json"),loadJSON("data/districts.json"),loadJSON("data/guides.json"),loadJSON("data/alerts.json")]);window.I18N=i;state.places=p;state.cities=c;state.districts=d;state.guides=g;state.alerts=a;buildFilters();applyI18n();$("#placeCount").textContent=p.length+"+";$("#cityCount").textContent=c.length+"+";$("#districtCount").textContent=d.length+"+";setView(state.view);loadMap();registerSW()}catch(e){console.error(e);$("#appError").textContent="Data loading error: "+e.message}}
async function setLang(lang){if(!["kr","ar","en"].includes(lang))return;state.lang=lang;localStorage.setItem("kt_lang",lang);try{window.I18N=await loadJSON("i18n/"+lang+".json");applyI18n();if(state.map)refreshMapPopups()}catch(e){console.error(e)}}
async function switchLang(){const order=["kr","ar","en"];await setLang(order[(order.indexOf(state.lang)+1)%3])}
function focusSearch(){$("#search")?.focus();$("#search")?.scrollIntoView({behavior:"smooth",block:"center"})}
function toggleMobileMenu(){$("#mobileMenu").classList.toggle("open")}
function setCategory(c){state.category=c;$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.cat===c));renderPlaces();updateSearchHint()}
function buildFilters(){const city=$("#cityFilter"),dist=$("#districtFilter");city.innerHTML='<option value="">'+t("all")+"</option>"+state.cities.map(c=>'<option value="'+esc(c.id)+'">'+esc(tx(c.name))+"</option>").join("");dist.innerHTML='<option value="">'+t("all")+"</option>"+state.districts.map(d=>'<option value="'+esc(d.id)+'">'+esc(tx(d.name))+"</option>").join("")}
function applyAdvancedFilters(){state.city=$("#cityFilter").value;state.district=$("#districtFilter").value;renderPlaces();updateSearchHint()}
function clearFilters(){state.category="all";state.city="";state.district="";state.query="";$("#search").value="";$("#cityFilter").value="";$("#districtFilter").value="";$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.cat==="all"));renderPlaces();updateSearchHint()}
function filteredPlaces(){let a=state.places.filter(p=>state.category==="all"||p.type===state.category);if(state.city)a=a.filter(p=>p.city===state.city);if(state.district)a=a.filter(p=>p.district===state.district);const q=state.query.trim().toLowerCase();if(q)a=a.filter(p=>(Object.values(p.name||{}).join(" ")+" "+Object.values(p.short||{}).join(" ")+" "+p.city+" "+p.district+" "+p.type).toLowerCase().includes(q));if(state.sort==="distance"&&state.user)a.sort((a,b)=>km(state.user.lat,state.user.lng,a.lat,a.lng)-km(state.user.lat,state.user.lng,b.lat,b.lng));return a}
function renderPlaces(){const grid=$("#placeGrid");if(!grid)return;grid.classList.toggle("listMode",state.view==="list");const a=filteredPlaces();grid.innerHTML=a.length?a.map(p=>{const dist=state.user?km(state.user.lat,state.user.lng,p.lat,p.lng).toFixed(1):null;const city=cityName(p.city),district=districtName(p.district);return '<article class="card"><div class="placePhoto"><img loading="lazy" onerror="this.onerror=null;this.src=\'assets/icon.svg\'" src="'+esc(p.images?.[0]||"assets/icon.svg")+'" alt="'+esc(tx(p.name))+'"><span class="badge">'+esc(typeLabel(p.type))+'</span><button class="fav" aria-label="favorite" onclick="toggleSaved(\''+esc(p.id)+'\')">'+(isSaved(p.id)?"♥":"♡")+'</button></div><div class="cardBody"><h3>'+esc(tx(p.name))+'</h3><div class="muted">📍 '+esc(city)+' · '+esc(district)+'</div><p class="muted">'+esc(tx(p.short))+'</p><div class="cardMeta"><span class="stars">★★★★★ '+esc(p.rating||"—")+'</span>'+(dist?'<span class="distance">'+dist+" "+t("km")+"</span>":"")+'</div><div class="cardActions"><button class="miniBtn" onclick="openPlace(\''+esc(p.id)+'\')">'+t("details")+'</button><a class="miniBtn" target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a><a class="miniBtn" target="_blank" rel="noopener" href="'+waze(p.lat,p.lng)+'">'+t("openWaze")+'</a></div></div></article>'}).join(""):'<div class="noResults">'+t("noResults")+"</div>";updateSearchHint()}
function updateSearchHint(){const el=$("#searchHint");if(!el)return;const n=filteredPlaces().length;el.textContent=n+" "+t("results")}
function liveSearch(){state.query=$("#search").value;renderPlaces()}
function cityName(id){const c=state.cities.find(x=>x.id===id);return c?tx(c.name):id}
function districtName(id){const d=state.districts.find(x=>x.id===id);return d?tx(d.name):id}
function renderCities(){const el=$("#cityGrid");if(!el)return;el.innerHTML=state.cities.map(c=>'<div class="cityCard"><span class="cityGov">'+esc(c.governorate||"")+'</span><h3>'+esc(tx(c.name))+'</h3><div class="muted">'+esc(tx(c.description))+'</div><p class="muted">📍 '+Number(c.lat).toFixed(3)+", "+Number(c.lng).toFixed(3)+'</p><button onclick="focusPlace('+c.lat+','+c.lng+')">'+t("map")+' →</button></div>').join("")}
function renderDistricts(){const el=$("#districtGrid");if(!el)return;const q=($("#districtSearch")?.value||"").trim().toLowerCase();const a=state.districts.filter(d=>(Object.values(d.name||{}).join(" ")+" "+d.gov).toLowerCase().includes(q));$("#districtResultCount").textContent=a.length+" "+t("districts");el.innerHTML=a.map(d=>'<div class="listItem"><h3>'+esc(tx(d.name))+'</h3><small>'+esc(d.gov)+'</small></div>').join("")||'<div class="noResults">'+t("noResults")+"</div>"}
function filterDistricts(){renderDistricts()}
function renderGuides(){const el=$("#guideGrid");if(!el)return;el.innerHTML=state.guides.map(g=>'<div class="guide"><div class="ico">'+esc(g.icon)+'</div><h3>'+esc(tx(g.title))+'</h3><ul>'+((g.items?.[state.lang]||g.items?.en||[]).map(x=>"<li>"+esc(x)+"</li>").join(""))+"</ul></div>").join("")}
function renderAlerts(){const el=$("#alerts");if(!el)return;el.innerHTML=state.alerts.map(a=>'<div class="alert '+(a.level==="warning"?"warning":"")+'"><small>'+esc(a.date||"")+'</small><h3>'+esc(tx(a.title))+'</h3><div class="muted">'+esc(tx(a.text))+'</div></div>').join("")}
function renderSaved(){const el=$("#saved");if(!el)return;const a=state.places.filter(p=>isSaved(p.id));el.innerHTML=a.length?a.map(p=>'<div class="listItem"><h3>'+esc(tx(p.name))+'</h3><small>'+esc(cityName(p.city))+' · <button class="miniBtn" onclick="openPlace(\''+esc(p.id)+'\')">'+t("details")+"</button></small></div>").join(""):'<div class="savedEmpty">'+t("savedTitle")+" — "+t("noResults")+"</div>"}
function openPlace(id){const p=state.places.find(x=>x.id===id);if(!p)return;const imgs=(p.images||[]).slice(0,5).map(x=>'<img loading="lazy" onerror="this.onerror=null;this.src=\'assets/icon.svg\'" src="'+esc(x)+'" alt="'+esc(tx(p.name))+'">').join("");const dist=state.user?'<div class="distance">📍 '+km(state.user.lat,state.user.lng,p.lat,p.lng).toFixed(1)+" "+t("km")+" "+t("nearby")+"</div>":"";$("#modal").classList.add("open");$("#modalContent").innerHTML='<div class="modalHead"><div><div class="eyebrow">'+esc(typeLabel(p.type))+'</div><h2>'+esc(tx(p.name))+'</h2></div><button class="close" onclick="closeModal()" aria-label="'+t("close")+'">×</button></div><div class="photoStrip">'+imgs+'</div><p class="muted">'+esc(tx(p.short))+'</p><div class="detailGrid"><div class="detailBox"><small>'+t("city")+'</small><b>'+esc(cityName(p.city))+'</b></div><div class="detailBox"><small>'+t("district")+'</small><b>'+esc(districtName(p.district))+'</b></div><div class="detailBox"><small>'+t("rating")+'</small><b>★ '+esc(p.rating||"—")+'</b></div><div class="detailBox"><small>'+t("coordinates")+'</small><b>'+Number(p.lat).toFixed(5)+", "+Number(p.lng).toFixed(5)+'</b></div></div>'+dist+'<div class="shareRow"><a class="btn primary" target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a><a class="btn ghost" target="_blank" rel="noopener" href="'+waze(p.lat,p.lng)+'">'+t("openWaze")+'</a><button class="btn ghost" onclick="sharePlace(\''+esc(p.id)+'\')">↗ '+t("share")+'</button><button class="btn ghost" onclick="copyCoords('+p.lat+','+p.lng+')">⌘ '+t("copyCoords")+'</button><button class="btn ghost" onclick="toggleSaved(\''+esc(p.id)+'\')">'+(isSaved(p.id)?"♥ ":"♡ ")+t("favorites")+'</button></div>'}
function closeModal(){$("#modal").classList.remove("open")}
async function sharePlace(id){const p=state.places.find(x=>x.id===id);if(!p)return;const data={title:tx(p.name),text:tx(p.short),url:location.href.split("#")[0]+"#place-"+encodeURIComponent(id)};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);alert(t("copied"))}}catch(e){}}
async function copyCoords(lat,lng){try{await navigator.clipboard.writeText(lat+","+lng);alert(t("copied"))}catch(e){prompt(t("copyCoords"),lat+","+lng)}}
function locateUser(){if(!navigator.geolocation){alert(t("locationDenied"));return}navigator.geolocation.getCurrentPosition(pos=>{state.user={lat:pos.coords.latitude,lng:pos.coords.longitude};renderPlaces();if(state.map){if(state.userMarker)state.map.removeLayer(state.userMarker);state.userMarker=L.circleMarker([state.user.lat,state.user.lng],{radius:9,color:"#35a874",fillColor:"#72d2a0",fillOpacity:.9,weight:3}).addTo(state.map).bindPopup("📍 "+t("myLocation")).openPopup();state.map.setView([state.user.lat,state.user.lng],11)}$("#locationText").textContent=state.user.lat.toFixed(4)+", "+state.user.lng.toFixed(4);},()=>alert(t("locationDenied")),{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
function focusPlace(lat,lng){$("#mapSection").scrollIntoView({behavior:"smooth"});if(state.map)state.map.setView([lat,lng],12)}
function doSearch(){state.query=$("#search").value;renderPlaces();$("#places").scrollIntoView({behavior:"smooth"})}
function sortPlaces(){state.sort=$("#sort").value;renderPlaces()}
function setView(v){state.view=v;localStorage.setItem("kt_view",v);$("#gridViewBtn")?.classList.toggle("active",v==="grid");$("#listViewBtn")?.classList.toggle("active",v==="list");$("#placeGrid")?.classList.toggle("listMode",v==="list");renderPlaces()}
function fitAll(){if(!state.map||!state.markers.length)return;const group=L.featureGroup(state.markers);state.map.fitBounds(group.getBounds().pad(.08))}
function refreshMapPopups(){state.markers.forEach((m,i)=>{const p=state.places[i];if(p)m.setPopupContent("<b>"+esc(tx(p.name))+"</b><br>"+esc(cityName(p.city))+"<br><a target='_blank' href='"+google(p.lat,p.lng)+"'>"+t("openGoogle")+"</a> · <a target='_blank' href='"+waze(p.lat,p.lng)+"'>"+t("openWaze")+"</a>")})}
function loadMap(){const fallback=()=>{const f=$("#mapFallback");f.innerHTML='<div class="fallbackGrid">'+state.places.map(p=>'<div class="fallbackItem"><b>'+esc(tx(p.name))+'</b><br><small>'+esc(cityName(p.city))+'</small><br><a target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a> · <a target="_blank" rel="noopener" href="'+waze(p.lat,p.lng)+'">'+t("openWaze")+'</a></div>').join("")+"</div>"};window.L?initLeaflet():loadLeaflet().then(initLeaflet).catch(fallback);function initLeaflet(){try{state.map=L.map("map",{scrollWheelZoom:true,zoomControl:true}).setView([36.2,44.2],7);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(state.map);state.markers=state.places.map(p=>{const m=L.marker([p.lat,p.lng]).addTo(state.map);m.bindPopup("<b>"+esc(tx(p.name))+"</b><br>"+esc(cityName(p.city))+"<br><a target='_blank' href='"+google(p.lat,p.lng)+"'>"+t("openGoogle")+"</a> · <a target='_blank' href='"+waze(p.lat,p.lng)+"'>"+t("openWaze")+"</a>");m.on("click",()=>{const card=state.places.find(x=>x.id===p.id);if(card)m.on("popupopen",()=>{});});return m});$("#mapFallback").style.display="none";fitAll();setTimeout(()=>state.map.invalidateSize(),400)}catch(e){fallback()}}}
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(css);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=resolve;s.onerror=reject;document.body.appendChild(s)})}
function registerSW(){if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{})}
document.addEventListener("click",e=>{if(e.target.id==="modal")closeModal();if(e.target.closest("#mobileMenu a"))$("#mobileMenu").classList.remove("open")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
window.addEventListener("load",boot);
Object.assign(window,{switchLang,setLang,setCategory,doSearch,liveSearch,sortPlaces,locateUser,toggleSaved,openPlace,closeModal,focusPlace,focusSearch,toggleMobileMenu,setView,applyAdvancedFilters,clearFilters,filterDistricts,fitAll,sharePlace,copyCoords});
