const state={lang:localStorage.getItem("kt_lang")||"kr",places:[],cities:[],districts:[],guides:[],alerts:[],category:"all",query:"",sort:"default",user:null,map:null,userMarker:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const t=k=>(window.I18N?.[k]||k);
function tx(obj){return obj?.[state.lang]||obj?.en||obj?.kr||""}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function km(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(c-a),dLon=rad(d-b),x=Math.sin(dLat/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function google(lat,lng){return "https://www.google.com/maps/dir/?api=1&destination="+lat+","+lng}
function waze(lat,lng){return "https://waze.com/ul?ll="+lat+","+lng+"&navigate=yes&utm_source=kurdistan_tourism"}
function isSaved(id){return JSON.parse(localStorage.getItem("kt_saved")||"[]").includes(id)}
function toggleSaved(id){let a=JSON.parse(localStorage.getItem("kt_saved")||"[]");a=a.includes(id)?a.filter(x=>x!==id):[...a,id];localStorage.setItem("kt_saved",JSON.stringify(a));renderPlaces();renderSaved()}
function typeLabel(type){return t(type)||type}
function applyI18n(){document.documentElement.lang=state.lang==="kr"?"ckb":state.lang;document.documentElement.dir=state.lang==="en"?"ltr":"rtl";$$("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));$$("[data-i18n-placeholder]").forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));$("#langBtn").textContent=state.lang.toUpperCase();renderPlaces();renderCities();renderDistricts();renderGuides();renderAlerts();renderSaved();if(state.map)state.map.eachLayer(layer=>{if(layer.getPopup)layer.getPopup()?.setContent(layer.getPopup().getContent())})}
async function loadJSON(p){const r=await fetch(p,{cache:"no-store"});if(!r.ok)throw Error(p+" "+r.status);return r.json()}
async function boot(){try{const [i,p,c,d,g,a]=await Promise.all([loadJSON("i18n/"+state.lang+".json"),loadJSON("data/places.json"),loadJSON("data/cities.json"),loadJSON("data/districts.json"),loadJSON("data/guides.json"),loadJSON("data/alerts.json")]);window.I18N=i;state.places=p;state.cities=c;state.districts=d;state.guides=g;state.alerts=a;applyI18n();$("#placeCount").textContent=p.length+"+";$("#cityCount").textContent=c.length+"+";$("#districtCount").textContent=d.length+"+";loadMap()}catch(e){console.error(e);$("#appError").textContent="Data loading error: "+e.message}}
async function switchLang(){const order=["kr","ar","en"];state.lang=order[(order.indexOf(state.lang)+1)%order.length];localStorage.setItem("kt_lang",state.lang);try{window.I18N=await loadJSON("i18n/"+state.lang+".json");applyI18n()}catch(e){console.error(e)}}
function setCategory(c){state.category=c;$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.cat===c));renderPlaces()}
function filteredPlaces(){let a=state.places.filter(p=>state.category==="all"||p.type===state.category);const q=state.query.trim().toLowerCase();if(q)a=a.filter(p=>(Object.values(p.name||{}).join(" ")+" "+Object.values(p.short||{}).join(" ")+" "+p.city+" "+p.district+" "+p.type).toLowerCase().includes(q));if(state.sort==="distance"&&state.user)a.sort((a,b)=>km(state.user.lat,state.user.lng,a.lat,a.lng)-km(state.user.lat,state.user.lng,b.lat,b.lng));return a}
function renderPlaces(){const grid=$("#placeGrid");if(!grid)return;const a=filteredPlaces();grid.innerHTML=a.length?a.map(p=>{const dist=state.user?km(state.user.lat,state.user.lng,p.lat,p.lng).toFixed(1):null;return '<article class="card"><div class="placePhoto"><img loading="lazy" src="'+esc(p.images[0])+'" alt="'+esc(tx(p.name))+'"><span class="badge">'+esc(typeLabel(p.type))+'</span><button class="fav" onclick="toggleSaved(\''+p.id+'\')">'+(isSaved(p.id)?"♥":"♡")+'</button></div><div class="cardBody"><h3>'+esc(tx(p.name))+'</h3><div class="muted">'+esc(cityName(p.city))+' · '+esc(districtName(p.district))+'</div><p class="muted">'+esc(tx(p.short))+'</p><div class="cardMeta"><span class="stars">★★★★★ '+p.rating+'</span>'+(dist?'<span class="distance">'+dist+" "+t("km")+"</span>":"")+'</div><div class="cardActions"><button class="miniBtn" onclick="openPlace(\''+p.id+'\')">'+t("details")+'</button><a class="miniBtn" target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a><a class="miniBtn" target="_blank" rel="noopener" href="'+waze(p.lat,p.lng)+'">'+t("openWaze")+'</a></div></div></article>'}).join(""):'<div class="noResults">'+t("noResults")+"</div>";}
function cityName(id){const c=state.cities.find(x=>x.id===id);return c?tx(c.name):id}
function districtName(id){const d=state.districts.find(x=>x.id===id);return d?tx(d.name):id}
function renderCities(){const el=$("#cityGrid");if(!el)return;el.innerHTML=state.cities.map(c=>'<div class="cityCard"><h3>'+esc(tx(c.name))+'</h3><div class="muted">'+esc(tx(c.description))+'</div><p class="muted">📍 '+c.lat.toFixed(3)+', '+c.lng.toFixed(3)+'</p><button onclick="focusPlace('+c.lat+','+c.lng+')">'+t("map")+' →</button></div>').join("")}
function renderDistricts(){const el=$("#districtGrid");if(!el)return;el.innerHTML=state.districts.map(d=>'<div class="listItem"><h3>'+esc(tx(d.name))+'</h3><small>'+esc(d.gov)+"</small></div>").join("")}
function renderGuides(){const el=$("#guideGrid");if(!el)return;el.innerHTML=state.guides.map(g=>'<div class="guide"><div class="ico">'+g.icon+'</div><h3>'+esc(tx(g.title))+'</h3><ul>'+g.items[state.lang].map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul></div>").join("")}
function renderAlerts(){const el=$("#alerts");if(!el)return;el.innerHTML=state.alerts.map(a=>'<div class="alert '+(a.level==="warning"?"warning":"")+'"><small>'+esc(a.date)+'</small><h3>'+esc(tx(a.title))+'</h3><div class="muted">'+esc(tx(a.text))+'</div></div>').join("")}
function renderSaved(){const el=$("#saved");if(!el)return;const ids=JSON.parse(localStorage.getItem("kt_saved")||"[]"),a=state.places.filter(p=>ids.includes(p.id));el.innerHTML=a.length?a.map(p=>'<div class="listItem"><h3>'+esc(tx(p.name))+'</h3><small>'+esc(cityName(p.city))+' · <button class="miniBtn" onclick="openPlace(\''+p.id+'\')">'+t("details")+"</button></small></div>").join(""):'<div class="savedEmpty">'+t("savedTitle")+" — "+t("noResults")+"</div>"}
function openPlace(id){const p=state.places.find(x=>x.id===id);if(!p)return;const imgs=p.images.slice(0,5).map(x=>'<img src="'+esc(x)+'" alt="'+esc(tx(p.name))+'">').join("");const dist=state.user?'<div class="distance">📍 '+km(state.user.lat,state.user.lng,p.lat,p.lng).toFixed(1)+" "+t("km")+" "+t("nearby")+"</div>":"";$("#modal").classList.add("open");$("#modalContent").innerHTML='<div class="modalHead"><div><div class="eyebrow">'+esc(typeLabel(p.type))+'</div><h2>'+esc(tx(p.name))+'</h2></div><button class="close" onclick="closeModal()">×</button></div><div class="photoStrip">'+imgs+'</div><p class="muted">'+esc(tx(p.short))+'</p>'+dist+'<div class="cardActions"><a class="btn primary" target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a><a class="btn ghost" target="_blank" rel="noopener" href="'+waze(p.lat,p.lng)+'">'+t("openWaze")+'</a><button class="btn ghost" onclick="toggleSaved(\''+p.id+'\');openPlace(\''+p.id+'\')">'+(isSaved(p.id)?t("savedTitle"):"♡ "+t("favorites"))+"</button></div>"}
function closeModal(){$("#modal").classList.remove("open")}
function locateUser(){if(!navigator.geolocation){alert(t("locationDenied"));return}navigator.geolocation.getCurrentPosition(pos=>{state.user={lat:pos.coords.latitude,lng:pos.coords.longitude};renderPlaces();renderSaved();if(state.map){if(state.userMarker)state.map.removeLayer(state.userMarker);state.userMarker=L.marker([state.user.lat,state.user.lng]).addTo(state.map).bindPopup("📍 "+t("myLocation")).openPopup();state.map.setView([state.user.lat,state.user.lng],11)}$("#locationText").textContent=state.user.lat.toFixed(4)+", "+state.user.lng.toFixed(4);},()=>alert(t("locationDenied")),{enableHighAccuracy:true,timeout:10000})}
function focusPlace(lat,lng){$("#mapSection").scrollIntoView({behavior:"smooth"});if(state.map){state.map.setView([lat,lng],12)}}
function doSearch(){state.query=$("#search").value;renderPlaces();$("#places").scrollIntoView({behavior:"smooth"})}
function sortPlaces(){state.sort=$("#sort").value;renderPlaces()}
function loadMap(){const fallback=()=>{const f=$("#mapFallback");f.innerHTML='<div class="fallbackGrid">'+state.places.map(p=>'<div class="fallbackItem"><b>'+esc(tx(p.name))+'</b><br><small>'+esc(cityName(p.city))+'</small><br><a target="_blank" rel="noopener" href="'+google(p.lat,p.lng)+'">'+t("openGoogle")+'</a></div>').join("")+"</div>"};window.L?initLeaflet():loadLeaflet().then(initLeaflet).catch(()=>fallback());function initLeaflet(){try{state.map=L.map("map",{scrollWheelZoom:true}).setView([36.25,44.35],8);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap contributors"}).addTo(state.map);state.places.forEach(p=>{const m=L.marker([p.lat,p.lng]).addTo(state.map);m.bindPopup("<b>"+esc(tx(p.name))+"</b><br>"+esc(cityName(p.city))+"<br><a target='_blank' href='"+google(p.lat,p.lng)+"'>"+t("openGoogle")+"</a> · <a target='_blank' href='"+waze(p.lat,p.lng)+"'>"+t("openWaze")+"</a>")});$("#mapFallback").style.display="none";setTimeout(()=>state.map.invalidateSize(),400)}catch(e){fallback()}}}
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";document.head.appendChild(css);const s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.onload=resolve;s.onerror=reject;document.body.appendChild(s)})}
document.addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
window.addEventListener("load",boot);
window.switchLang=switchLang;window.setCategory=setCategory;window.doSearch=doSearch;window.sortPlaces=sortPlaces;window.locateUser=locateUser;window.toggleSaved=toggleSaved;window.openPlace=openPlace;window.closeModal=closeModal;window.focusPlace=focusPlace;